CREATE TABLE makosh_data.mail_contacts_sync_reverse_inbox (
    logical_owner_id TEXT NOT NULL,
    event_message_id BYTEA NOT NULL,
    event_envelope_sha256 BYTEA NOT NULL,
    completed_at_unix_millis BIGINT NOT NULL,
    PRIMARY KEY (logical_owner_id, event_message_id),
    CHECK (length(logical_owner_id) BETWEEN 1 AND 128),
    CHECK (length(event_message_id) = 16),
    CHECK (length(event_envelope_sha256) = 32),
    CHECK (completed_at_unix_millis > 0)
);
CREATE TABLE makosh_data.mail_contacts_sync_reverse_operations (
    logical_owner_id TEXT NOT NULL,
    operation_id BYTEA NOT NULL,
    source_event_message_id BYTEA NOT NULL,
    configuration_instance_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    contact_id BYTEA NOT NULL,
    contact_revision BIGINT NOT NULL,
    state SMALLINT NOT NULL,
    source_command_message_id BYTEA NOT NULL,
    mail_command_message_id BYTEA,
    terminal_message_id BYTEA,
    created_at_unix_millis BIGINT NOT NULL,
    updated_at_unix_millis BIGINT NOT NULL,
    PRIMARY KEY (logical_owner_id, operation_id),
    UNIQUE (logical_owner_id, configuration_instance_id, contact_id, contact_revision),
    CHECK (length(logical_owner_id) BETWEEN 1 AND 128),
    CHECK (length(operation_id) = 16),
    CHECK (length(source_event_message_id) = 16),
    CHECK (length(configuration_instance_id) BETWEEN 1 AND 128),
    CHECK (length(account_id) BETWEEN 1 AND 256),
    CHECK (length(contact_id) = 16),
    CHECK (contact_revision > 0),
    CHECK (state IN (1, 2, 3, 4, 5)),
    CHECK (length(source_command_message_id) = 16),
    CHECK (mail_command_message_id IS NULL OR length(mail_command_message_id) = 16),
    CHECK (terminal_message_id IS NULL OR length(terminal_message_id) = 16),
    CHECK (created_at_unix_millis > 0),
    CHECK (updated_at_unix_millis >= created_at_unix_millis)
);
