import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'

describe('Макошь UI editor component contracts', () => {
	it('keeps RichTextEditor documented and exported through the UI kit', () => {
		const uiRoot = fileURLToPath(new URL('.', import.meta.url))
		const barrel = readFileSync(join(uiRoot, 'index.ts'), 'utf8')

		expect(existsSync(join(uiRoot, 'RichTextEditor.vue'))).toBe(true)
		expect(existsSync(join(uiRoot, 'RichTextEditor.README.md'))).toBe(true)
		expect(barrel).toContain("export { default as RichTextEditor } from './RichTextEditor.vue'")
		expect(barrel).toContain("export type { RichTextEditorAction, RichTextEditorToolbarAction } from './RichTextEditor.types'")
	})

	it('keeps the editor UI-only and provider neutral', () => {
		const uiRoot = fileURLToPath(new URL('.', import.meta.url))
		const componentSource = readFileSync(join(uiRoot, 'RichTextEditor.vue'), 'utf8')
		const extensionSource = readFileSync(join(uiRoot, 'RichTextEditor.extensions.ts'), 'utf8')
		const forbiddenSource = /@\/domains|@\/integrations|@\/platform|fetch\(|useQuery|defineStore|createRouter|localStorage/

		expect(componentSource).not.toMatch(forbiddenSource)
		expect(extensionSource).not.toMatch(/domains\/communications/)
		expect(componentSource).toContain("from '@tiptap/vue-3'")
		expect(componentSource).toContain('sanitizeHtml')
		expect(componentSource).toContain('Tooltip')
		expect(componentSource).toContain('IconButton')
		expect(extensionSource).toContain("name: 'orderedList'")
		expect(extensionSource).toContain("name: 'codeBlock'")
		expect(extensionSource).toContain("name: 'underline'")
		expect(componentSource).toContain('clearFormatting')
	})

	it('keeps the editor represented in Storybook with localized text', () => {
		const storySource = readFileSync(
			fileURLToPath(new URL('../../../stories/ui/Editor.stories.ts', import.meta.url)),
			'utf8'
		)
		const i18nSource = readFileSync(
			fileURLToPath(new URL('../../../stories/ui/storybook-i18n.ts', import.meta.url)),
			'utf8'
		)

		expect(storySource).toContain('RichTextEditor')
		expect(storySource).toContain('HtmlPreview')
		expect(storySource).toContain("from './storybook-i18n'")
		expect(i18nSource).toContain('editor: {')
		expect(i18nSource).toContain('Rich context editor')
		expect(i18nSource).toContain('Editor de contexto enriquecido')
		expect(i18nSource).toContain('Редактор контекста')
	})

	it('replaces empty autogenerated docs tabs with one authored docs page', () => {
		const storiesRoot = fileURLToPath(new URL('../../../stories/ui/', import.meta.url))
		const storybookMain = readFileSync(
			fileURLToPath(new URL('../../../.storybook/main.ts', import.meta.url)),
			'utf8'
		)
		const storySources = readdirSync(storiesRoot)
			.filter((fileName) => fileName.endsWith('.stories.ts'))
			.map((fileName) => readFileSync(join(storiesRoot, fileName), 'utf8'))
			.join('\n')
		const docsSource = readFileSync(join(storiesRoot, 'Docs.mdx'), 'utf8')

		expect(storySources).not.toContain("tags: ['autodocs']")
		expect(storySources).not.toContain('tags: ["autodocs"]')
		expect(storybookMain).toContain("'../stories/**/*.mdx'")
		expect(docsSource).toContain('<Meta title="Макошь UI/Docs" />')
	})
})
