[package]
name = "makosh-vault-api"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
publish = false
license = "MIT"
[dependencies]
chrono = { version = "0.4", default-features = false, features = ["serde"] }
makosh-provider-api = { path = "../provider-api" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
