//! Mail-owned operational projection and atomic Communications outbox handoff.

use std::collections::{BTreeMap, BTreeSet};

use hermes_events_protocol::delivery::OutboxRecordV1;
use hermes_mail_api::operational::{
    MailFolderKindV1, MailFolderV1, MailMessageDetailV1, MailMessageFlagV1, MailMessageSummaryV1,
    MailOperationalPageV1, MailOperationalQueryResponseV1, MailOperationalQueryV1, MailThreadV1,
    validate_operational_message, validate_operational_query,
};
use sha2::{Digest, Sha256};
use sqlx::{Postgres, Row, Transaction, postgres::PgRow};

use crate::{
    MailDurablePersistence, MailDurablePersistenceError, MailImapMessageLocatorV1,
    durable::insert_communications_outbox,
    provider_location::{upsert_imap_message_locator, validate_imap_locator},
};

pub const MAIL_SCHEMA_V9: &str = r#"
CREATE TABLE IF NOT EXISTS hermes_data.mail_operational_folders (
    connection_id TEXT NOT NULL,
    folder_id TEXT NOT NULL,
    display_name TEXT NOT NULL,
    kind SMALLINT NOT NULL,
    total_messages BIGINT NOT NULL DEFAULT 0,
    unread_messages BIGINT NOT NULL DEFAULT 0,
    projection_revision BIGINT NOT NULL DEFAULT 1,
    updated_at_unix_seconds BIGINT NOT NULL,
    cursor_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    PRIMARY KEY (connection_id, folder_id),
    CHECK (connection_id <> ''),
    CHECK (folder_id <> ''),
    CHECK (display_name <> ''),
    CHECK (kind BETWEEN 1 AND 7),
    CHECK (total_messages >= 0),
    CHECK (unread_messages >= 0 AND unread_messages <= total_messages),
    CHECK (projection_revision > 0),
    CHECK (updated_at_unix_seconds > 0)
);
CREATE INDEX IF NOT EXISTS mail_operational_folders_cursor_idx
    ON hermes_data.mail_operational_folders
    (connection_id, updated_at_unix_seconds DESC, cursor_sequence DESC);
CREATE TABLE IF NOT EXISTS hermes_data.mail_operational_threads (
    connection_id TEXT NOT NULL,
    provider_thread_id TEXT NOT NULL,
    subject TEXT,
    latest_snippet TEXT,
    latest_at_unix_seconds BIGINT,
    message_count BIGINT NOT NULL,
    unread_count BIGINT NOT NULL,
    projection_revision BIGINT NOT NULL DEFAULT 1,
    updated_at_unix_seconds BIGINT NOT NULL,
    cursor_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    PRIMARY KEY (connection_id, provider_thread_id),
    CHECK (connection_id <> ''),
    CHECK (provider_thread_id <> ''),
    CHECK (message_count > 0),
    CHECK (unread_count >= 0 AND unread_count <= message_count),
    CHECK (projection_revision > 0),
    CHECK (updated_at_unix_seconds > 0)
);
CREATE INDEX IF NOT EXISTS mail_operational_threads_cursor_idx
    ON hermes_data.mail_operational_threads
    (connection_id, updated_at_unix_seconds DESC, cursor_sequence DESC);
CREATE TABLE IF NOT EXISTS hermes_data.mail_operational_messages (
    connection_id TEXT NOT NULL,
    provider_message_id TEXT NOT NULL,
    provider_thread_id TEXT NOT NULL,
    subject TEXT,
    sender TEXT,
    recipients TEXT[] NOT NULL,
    snippet TEXT,
    sent_at_unix_seconds BIGINT,
    flags SMALLINT[] NOT NULL,
    has_plain_text BOOLEAN NOT NULL,
    has_attachments BOOLEAN NOT NULL,
    observation_anchor_id BYTEA NOT NULL,
    projection_revision BIGINT NOT NULL DEFAULT 1,
    updated_at_unix_seconds BIGINT NOT NULL,
    cursor_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    PRIMARY KEY (connection_id, provider_message_id),
    CHECK (connection_id <> ''),
    CHECK (provider_message_id <> ''),
    CHECK (provider_thread_id <> ''),
    CHECK (octet_length(observation_anchor_id) = 16),
    CHECK (projection_revision > 0),
    CHECK (updated_at_unix_seconds > 0)
);
CREATE INDEX IF NOT EXISTS mail_operational_messages_thread_idx
    ON hermes_data.mail_operational_messages
    (connection_id, provider_thread_id, updated_at_unix_seconds DESC, provider_message_id DESC);
CREATE INDEX IF NOT EXISTS mail_operational_messages_cursor_idx
    ON hermes_data.mail_operational_messages
    (connection_id, updated_at_unix_seconds DESC, cursor_sequence DESC);
CREATE TABLE IF NOT EXISTS hermes_data.mail_operational_message_folders (
    connection_id TEXT NOT NULL,
    provider_message_id TEXT NOT NULL,
    folder_id TEXT NOT NULL,
    PRIMARY KEY (connection_id, provider_message_id, folder_id),
    FOREIGN KEY (connection_id, provider_message_id)
        REFERENCES hermes_data.mail_operational_messages (connection_id, provider_message_id)
        ON DELETE CASCADE,
    FOREIGN KEY (connection_id, folder_id)
        REFERENCES hermes_data.mail_operational_folders (connection_id, folder_id)
        ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS mail_operational_message_folders_folder_idx
    ON hermes_data.mail_operational_message_folders
    (connection_id, folder_id, provider_message_id);
"#;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MailOperationalFolderSnapshotV1 {
    pub folder_id: String,
    pub display_name: String,
    pub kind: MailFolderKindV1,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MailOperationalMessageSnapshotV1 {
    pub connection_id: String,
    pub message_id: String,
    pub imap_locator: Option<MailImapMessageLocatorV1>,
    pub provider_thread_id: String,
    pub folders: Vec<MailOperationalFolderSnapshotV1>,
    pub subject: Option<String>,
    pub sender: Option<String>,
    pub recipients: Vec<String>,
    pub snippet: Option<String>,
    pub sent_at_unix_seconds: Option<i64>,
    pub flags: Vec<MailMessageFlagV1>,
    pub has_plain_text: bool,
    pub has_attachments: bool,
    pub observation_anchor_id: [u8; 16],
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MailOperationalMaterializationV1 {
    pub message: MailOperationalMessageSnapshotV1,
    pub delivery_route_locator: crate::MailDeliveryRouteLocatorV1,
    pub communications_outbox: Vec<OutboxRecordV1>,
}

impl MailDurablePersistence {
    pub async fn record_operational_materializations(
        &self,
        materializations: &[MailOperationalMaterializationV1],
        observed_at_unix_seconds: i64,
    ) -> Result<(), MailDurablePersistenceError> {
        validate_materializations(materializations, observed_at_unix_seconds)?;
        let mut transaction = self
            .pool
            .begin()
            .await
            .map_err(|_| MailDurablePersistenceError::Database)?;
        record_operational_materializations_in_transaction(
            &mut transaction,
            materializations,
            observed_at_unix_seconds,
        )
        .await?;
        transaction
            .commit()
            .await
            .map_err(|_| MailDurablePersistenceError::Database)
    }

    pub async fn record_operational_folders(
        &self,
        connection_id: &str,
        folders: &[MailOperationalFolderSnapshotV1],
        observed_at_unix_seconds: i64,
    ) -> Result<(), MailDurablePersistenceError> {
        if connection_id.trim().is_empty()
            || connection_id.len() > 512
            || connection_id.contains(['\0', '\r', '\n'])
            || connection_id.trim() != connection_id
            || folders.is_empty()
            || folders.len() > 256
            || folders.iter().any(|folder| !valid_folder_snapshot(folder))
            || observed_at_unix_seconds <= 0
        {
            return Err(MailDurablePersistenceError::InvalidRow);
        }
        let mut transaction = self
            .pool
            .begin()
            .await
            .map_err(|_| MailDurablePersistenceError::Database)?;
        for folder in folders {
            upsert_operational_folder(
                &mut transaction,
                connection_id,
                folder,
                observed_at_unix_seconds,
            )
            .await?;
        }
        transaction
            .commit()
            .await
            .map_err(|_| MailDurablePersistenceError::Database)
    }

    pub async fn execute_operational_query(
        &self,
        query: &MailOperationalQueryV1,
    ) -> Result<MailOperationalQueryResponseV1, MailDurablePersistenceError> {
        validate_operational_query(query).map_err(|_| MailDurablePersistenceError::InvalidRow)?;
        match query {
            MailOperationalQueryV1::ListFolders {
                connection_id,
                cursor,
                limit,
            } => {
                self.list_operational_folders(connection_id, cursor.as_deref(), *limit)
                    .await
            }
            MailOperationalQueryV1::ListThreads {
                connection_id,
                folder_id,
                cursor,
                limit,
            } => {
                self.list_operational_threads(
                    connection_id,
                    folder_id.as_deref(),
                    cursor.as_deref(),
                    *limit,
                )
                .await
            }
            MailOperationalQueryV1::ListMessages {
                connection_id,
                folder_id,
                provider_thread_id,
                cursor,
                limit,
            } => {
                self.list_operational_messages(
                    connection_id,
                    folder_id.as_deref(),
                    provider_thread_id.as_deref(),
                    cursor.as_deref(),
                    *limit,
                )
                .await
            }
            MailOperationalQueryV1::GetMessage {
                connection_id,
                message_id,
            } => {
                let summary = self.operational_message(connection_id, message_id).await?;
                Ok(MailOperationalQueryResponseV1::Message(Box::new(
                    MailMessageDetailV1 { summary },
                )))
            }
        }
    }

    async fn list_operational_folders(
        &self,
        connection_id: &str,
        cursor: Option<&str>,
        limit: u32,
    ) -> Result<MailOperationalQueryResponseV1, MailDurablePersistenceError> {
        let scope = cursor_scope(&["folders", connection_id]);
        let anchor = decode_cursor("m1f", &scope, cursor)?;
        if cursor.is_some() {
            require_cursor_anchor(
                sqlx::query(
                    "SELECT EXISTS(SELECT 1 FROM hermes_data.mail_operational_folders \
                     WHERE connection_id = $1 AND updated_at_unix_seconds = $2 \
                       AND cursor_sequence = $3) AS present",
                )
                .bind(connection_id)
                .bind(anchor.updated_at_unix_seconds)
                .bind(anchor.sequence)
                .fetch_one(&self.pool)
                .await,
            )?;
        }
        let rows = sqlx::query(
            "SELECT connection_id, folder_id, display_name, kind, total_messages, \
             unread_messages, projection_revision, updated_at_unix_seconds, cursor_sequence \
             FROM hermes_data.mail_operational_folders WHERE connection_id = $1 \
               AND (updated_at_unix_seconds, cursor_sequence) < ($2, $3) \
             ORDER BY updated_at_unix_seconds DESC, cursor_sequence DESC LIMIT $4",
        )
        .bind(connection_id)
        .bind(anchor.updated_at_unix_seconds)
        .bind(anchor.sequence)
        .bind(i64::from(limit))
        .fetch_all(&self.pool)
        .await
        .map_err(|_| MailDurablePersistenceError::Database)?;
        let items = rows
            .iter()
            .map(folder_from_row)
            .collect::<Result<Vec<_>, _>>()?;
        let next_cursor = page_cursor("m1f", &scope, &rows, limit)?;
        Ok(MailOperationalQueryResponseV1::Folders(
            MailOperationalPageV1 { items, next_cursor },
        ))
    }

    async fn list_operational_threads(
        &self,
        connection_id: &str,
        folder_id: Option<&str>,
        cursor: Option<&str>,
        limit: u32,
    ) -> Result<MailOperationalQueryResponseV1, MailDurablePersistenceError> {
        let scope = cursor_scope(&["threads", connection_id, folder_id.unwrap_or("")]);
        let anchor = decode_cursor("m1t", &scope, cursor)?;
        if cursor.is_some() {
            require_cursor_anchor(
                sqlx::query(
                    "SELECT EXISTS(SELECT 1 FROM hermes_data.mail_operational_threads AS thread \
                     WHERE thread.connection_id = $1 AND thread.updated_at_unix_seconds = $2 \
                       AND thread.cursor_sequence = $3 AND ($4::TEXT IS NULL OR EXISTS( \
                         SELECT 1 FROM hermes_data.mail_operational_messages AS message \
                         JOIN hermes_data.mail_operational_message_folders AS membership \
                           ON membership.connection_id = message.connection_id \
                          AND membership.message_id = message.message_id \
                         WHERE message.connection_id = thread.connection_id \
                           AND message.provider_thread_id = thread.provider_thread_id \
                           AND membership.folder_id = $4))) AS present",
                )
                .bind(connection_id)
                .bind(anchor.updated_at_unix_seconds)
                .bind(anchor.sequence)
                .bind(folder_id)
                .fetch_one(&self.pool)
                .await,
            )?;
        }
        let rows = sqlx::query(
            "SELECT thread.connection_id, thread.provider_thread_id, thread.subject, \
             thread.latest_snippet, thread.latest_at_unix_seconds, thread.message_count, \
             thread.unread_count, thread.projection_revision, thread.updated_at_unix_seconds, \
             thread.cursor_sequence FROM hermes_data.mail_operational_threads AS thread \
             WHERE thread.connection_id = $1 AND ($2::TEXT IS NULL OR EXISTS( \
               SELECT 1 FROM hermes_data.mail_operational_messages AS message \
               JOIN hermes_data.mail_operational_message_folders AS membership \
                 ON membership.connection_id = message.connection_id \
                AND membership.message_id = message.message_id \
               WHERE message.connection_id = thread.connection_id \
                 AND message.provider_thread_id = thread.provider_thread_id \
                 AND membership.folder_id = $2)) \
               AND (thread.updated_at_unix_seconds, thread.cursor_sequence) < ($3, $4) \
             ORDER BY thread.updated_at_unix_seconds DESC, thread.cursor_sequence DESC LIMIT $5",
        )
        .bind(connection_id)
        .bind(folder_id)
        .bind(anchor.updated_at_unix_seconds)
        .bind(anchor.sequence)
        .bind(i64::from(limit))
        .fetch_all(&self.pool)
        .await
        .map_err(|_| MailDurablePersistenceError::Database)?;
        let items = rows
            .iter()
            .map(thread_from_row)
            .collect::<Result<Vec<_>, _>>()?;
        let next_cursor = page_cursor("m1t", &scope, &rows, limit)?;
        Ok(MailOperationalQueryResponseV1::Threads(
            MailOperationalPageV1 { items, next_cursor },
        ))
    }

    async fn list_operational_messages(
        &self,
        connection_id: &str,
        folder_id: Option<&str>,
        provider_thread_id: Option<&str>,
        cursor: Option<&str>,
        limit: u32,
    ) -> Result<MailOperationalQueryResponseV1, MailDurablePersistenceError> {
        let scope = cursor_scope(&[
            "messages",
            connection_id,
            folder_id.unwrap_or(""),
            provider_thread_id.unwrap_or(""),
        ]);
        let anchor = decode_cursor("m2m", &scope, cursor)?;
        if cursor.is_some() {
            require_cursor_anchor(
                sqlx::query(
                    "SELECT EXISTS(SELECT 1 FROM hermes_data.mail_operational_messages AS message \
                     WHERE message.connection_id = $1 \
                       AND COALESCE(message.sent_at_unix_seconds, 1) = $2 \
                       AND message.cursor_sequence = $3 \
                       AND ($4::TEXT IS NULL OR message.provider_thread_id = $4) \
                       AND ($5::TEXT IS NULL OR EXISTS( \
                         SELECT 1 FROM hermes_data.mail_operational_message_folders AS membership \
                         WHERE membership.connection_id = message.connection_id \
                           AND membership.message_id = message.message_id \
                           AND membership.folder_id = $5))) AS present",
                )
                .bind(connection_id)
                .bind(anchor.updated_at_unix_seconds)
                .bind(anchor.sequence)
                .bind(provider_thread_id)
                .bind(folder_id)
                .fetch_one(&self.pool)
                .await,
            )?;
        }
        let rows = sqlx::query(
            "SELECT message.connection_id, message.message_id, \
             message.provider_thread_id, message.subject, message.sender, message.recipients, \
             message.snippet, message.sent_at_unix_seconds, message.flags, \
             message.has_plain_text, message.has_attachments, message.observation_anchor_id, \
             message.projection_revision, message.updated_at_unix_seconds, \
             COALESCE(message.sent_at_unix_seconds, 1) AS message_order_unix_seconds, \
             message.cursor_sequence FROM hermes_data.mail_operational_messages AS message \
             WHERE message.connection_id = $1 \
               AND ($2::TEXT IS NULL OR message.provider_thread_id = $2) \
               AND ($3::TEXT IS NULL OR EXISTS( \
                 SELECT 1 FROM hermes_data.mail_operational_message_folders AS membership \
                 WHERE membership.connection_id = message.connection_id \
                   AND membership.message_id = message.message_id \
                   AND membership.folder_id = $3)) \
               AND (COALESCE(message.sent_at_unix_seconds, 1), message.cursor_sequence) < ($4, $5) \
             ORDER BY COALESCE(message.sent_at_unix_seconds, 1) DESC, \
                      message.cursor_sequence DESC LIMIT $6",
        )
        .bind(connection_id)
        .bind(provider_thread_id)
        .bind(folder_id)
        .bind(anchor.updated_at_unix_seconds)
        .bind(anchor.sequence)
        .bind(i64::from(limit))
        .fetch_all(&self.pool)
        .await
        .map_err(|_| MailDurablePersistenceError::Database)?;
        let folder_ids = self
            .operational_folder_ids(connection_id, message_ids(&rows)?)
            .await?;
        let items = rows
            .iter()
            .map(|row| message_from_row(row, &folder_ids))
            .collect::<Result<Vec<_>, _>>()?;
        let next_cursor = message_page_cursor("m2m", &scope, &rows, limit)?;
        Ok(MailOperationalQueryResponseV1::Messages(
            MailOperationalPageV1 { items, next_cursor },
        ))
    }

    async fn operational_message(
        &self,
        connection_id: &str,
        message_id: &str,
    ) -> Result<MailMessageSummaryV1, MailDurablePersistenceError> {
        let row = sqlx::query(
            "SELECT connection_id, message_id, provider_thread_id, subject, sender, \
             recipients, snippet, sent_at_unix_seconds, flags, has_plain_text, has_attachments, \
             observation_anchor_id, projection_revision FROM \
             hermes_data.mail_operational_messages \
             WHERE connection_id = $1 AND message_id = $2",
        )
        .bind(connection_id)
        .bind(message_id)
        .fetch_optional(&self.pool)
        .await
        .map_err(|_| MailDurablePersistenceError::Database)?
        .ok_or(MailDurablePersistenceError::MissingOperationalMessage)?;
        let folder_ids = self
            .operational_folder_ids(connection_id, vec![message_id.to_owned()])
            .await?;
        message_from_row(&row, &folder_ids)
    }

    async fn operational_folder_ids(
        &self,
        connection_id: &str,
        message_ids: Vec<String>,
    ) -> Result<BTreeMap<String, Vec<String>>, MailDurablePersistenceError> {
        if message_ids.is_empty() {
            return Ok(BTreeMap::new());
        }
        let rows = sqlx::query(
            "SELECT message_id, folder_id FROM \
             hermes_data.mail_operational_message_folders \
             WHERE connection_id = $1 AND message_id = ANY($2) \
             ORDER BY message_id, folder_id",
        )
        .bind(connection_id)
        .bind(message_ids)
        .fetch_all(&self.pool)
        .await
        .map_err(|_| MailDurablePersistenceError::Database)?;
        let mut folder_ids = BTreeMap::<String, Vec<String>>::new();
        for row in &rows {
            folder_ids
                .entry(row_string(row, "message_id")?)
                .or_default()
                .push(row_string(row, "folder_id")?);
        }
        Ok(folder_ids)
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct CursorAnchorV1 {
    updated_at_unix_seconds: i64,
    sequence: i64,
}

fn cursor_scope(parts: &[&str]) -> String {
    let mut digest = Sha256::new();
    for part in parts {
        digest.update((part.len() as u64).to_be_bytes());
        digest.update(part.as_bytes());
    }
    digest
        .finalize()
        .iter()
        .take(8)
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

fn decode_cursor(
    prefix: &str,
    scope: &str,
    cursor: Option<&str>,
) -> Result<CursorAnchorV1, MailDurablePersistenceError> {
    let Some(cursor) = cursor else {
        return Ok(CursorAnchorV1 {
            updated_at_unix_seconds: i64::MAX,
            sequence: i64::MAX,
        });
    };
    let parts = cursor.split('.').collect::<Vec<_>>();
    if parts.len() != 4 || parts[0] != prefix || parts[1] != scope {
        return Err(MailDurablePersistenceError::InvalidRow);
    }
    let updated_at_unix_seconds = parts[2]
        .parse::<i64>()
        .ok()
        .filter(|value| *value > 0)
        .ok_or(MailDurablePersistenceError::InvalidRow)?;
    let sequence = parts[3]
        .parse::<i64>()
        .ok()
        .filter(|value| *value > 0)
        .ok_or(MailDurablePersistenceError::InvalidRow)?;
    Ok(CursorAnchorV1 {
        updated_at_unix_seconds,
        sequence,
    })
}

fn encode_cursor(
    prefix: &str,
    scope: &str,
    row: &PgRow,
) -> Result<String, MailDurablePersistenceError> {
    Ok(format!(
        "{prefix}.{scope}.{}.{}",
        row_i64(row, "updated_at_unix_seconds")?,
        row_i64(row, "cursor_sequence")?
    ))
}

fn page_cursor(
    prefix: &str,
    scope: &str,
    rows: &[PgRow],
    limit: u32,
) -> Result<Option<String>, MailDurablePersistenceError> {
    (rows.len() == limit as usize)
        .then(|| rows.last())
        .flatten()
        .map(|row| encode_cursor(prefix, scope, row))
        .transpose()
}

fn message_page_cursor(
    prefix: &str,
    scope: &str,
    rows: &[PgRow],
    limit: u32,
) -> Result<Option<String>, MailDurablePersistenceError> {
    (rows.len() == limit as usize)
        .then(|| rows.last())
        .flatten()
        .map(|row| {
            Ok(format!(
                "{prefix}.{scope}.{}.{}",
                row_i64(row, "message_order_unix_seconds")?,
                row_i64(row, "cursor_sequence")?
            ))
        })
        .transpose()
}

fn require_cursor_anchor(
    row: Result<PgRow, sqlx::Error>,
) -> Result<(), MailDurablePersistenceError> {
    let row = row.map_err(|_| MailDurablePersistenceError::Database)?;
    if row_bool(&row, "present")? {
        Ok(())
    } else {
        Err(MailDurablePersistenceError::InvalidRow)
    }
}

fn message_ids(rows: &[PgRow]) -> Result<Vec<String>, MailDurablePersistenceError> {
    rows.iter()
        .map(|row| row_string(row, "message_id"))
        .collect()
}

fn folder_from_row(row: &PgRow) -> Result<MailFolderV1, MailDurablePersistenceError> {
    let folder = MailFolderV1 {
        connection_id: row_string(row, "connection_id")?,
        folder_id: row_string(row, "folder_id")?,
        display_name: row_string(row, "display_name")?,
        kind: folder_kind_from_id(row_i16(row, "kind")?)?,
        total_messages: row_u64(row, "total_messages")?,
        unread_messages: row_u64(row, "unread_messages")?,
        projection_revision: row_u64(row, "projection_revision")?,
    };
    if folder.connection_id.is_empty()
        || folder.folder_id.is_empty()
        || folder.display_name.is_empty()
        || folder.unread_messages > folder.total_messages
        || folder.projection_revision == 0
    {
        return Err(MailDurablePersistenceError::InvalidRow);
    }
    Ok(folder)
}

fn thread_from_row(row: &PgRow) -> Result<MailThreadV1, MailDurablePersistenceError> {
    let thread = MailThreadV1 {
        connection_id: row_string(row, "connection_id")?,
        provider_thread_id: row_string(row, "provider_thread_id")?,
        subject: row_optional_string(row, "subject")?,
        latest_snippet: row_optional_string(row, "latest_snippet")?,
        latest_at_unix_seconds: row_optional_i64(row, "latest_at_unix_seconds")?,
        message_count: row_u64(row, "message_count")?,
        unread_count: row_u64(row, "unread_count")?,
        projection_revision: row_u64(row, "projection_revision")?,
    };
    if thread.connection_id.is_empty()
        || thread.provider_thread_id.is_empty()
        || thread.message_count == 0
        || thread.unread_count > thread.message_count
        || thread.projection_revision == 0
    {
        return Err(MailDurablePersistenceError::InvalidRow);
    }
    Ok(thread)
}

fn message_from_row(
    row: &PgRow,
    folder_ids: &BTreeMap<String, Vec<String>>,
) -> Result<MailMessageSummaryV1, MailDurablePersistenceError> {
    let message_id = row_string(row, "message_id")?;
    let observation_anchor = row_bytes(row, "observation_anchor_id")?;
    let observation_anchor_id = <[u8; 16]>::try_from(observation_anchor.as_slice())
        .map_err(|_| MailDurablePersistenceError::InvalidRow)?;
    let flags = row
        .try_get::<Vec<i16>, _>("flags")
        .map_err(|_| MailDurablePersistenceError::InvalidRow)?
        .into_iter()
        .map(message_flag_from_id)
        .collect::<Result<Vec<_>, _>>()?;
    let message = MailMessageSummaryV1 {
        connection_id: row_string(row, "connection_id")?,
        message_id: message_id.clone(),
        provider_thread_id: row_string(row, "provider_thread_id")?,
        folder_ids: folder_ids
            .get(&message_id)
            .cloned()
            .ok_or(MailDurablePersistenceError::InvalidRow)?,
        subject: row_optional_string(row, "subject")?,
        sender: row_optional_string(row, "sender")?,
        recipients: row
            .try_get::<Vec<String>, _>("recipients")
            .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        snippet: row_optional_string(row, "snippet")?,
        sent_at_unix_seconds: row_optional_i64(row, "sent_at_unix_seconds")?,
        flags,
        has_plain_text: row_bool(row, "has_plain_text")?,
        has_attachments: row_bool(row, "has_attachments")?,
        observation_anchor_id,
        projection_revision: row_u64(row, "projection_revision")?,
    };
    validate_operational_message(&message).map_err(|_| MailDurablePersistenceError::InvalidRow)?;
    Ok(message)
}

fn row_string(row: &PgRow, column: &str) -> Result<String, MailDurablePersistenceError> {
    row.try_get(column)
        .map_err(|_| MailDurablePersistenceError::InvalidRow)
}

fn row_optional_string(
    row: &PgRow,
    column: &str,
) -> Result<Option<String>, MailDurablePersistenceError> {
    row.try_get(column)
        .map_err(|_| MailDurablePersistenceError::InvalidRow)
}

fn row_i16(row: &PgRow, column: &str) -> Result<i16, MailDurablePersistenceError> {
    row.try_get(column)
        .map_err(|_| MailDurablePersistenceError::InvalidRow)
}

fn row_i64(row: &PgRow, column: &str) -> Result<i64, MailDurablePersistenceError> {
    row.try_get(column)
        .map_err(|_| MailDurablePersistenceError::InvalidRow)
}

fn row_optional_i64(row: &PgRow, column: &str) -> Result<Option<i64>, MailDurablePersistenceError> {
    row.try_get(column)
        .map_err(|_| MailDurablePersistenceError::InvalidRow)
}

fn row_u64(row: &PgRow, column: &str) -> Result<u64, MailDurablePersistenceError> {
    u64::try_from(row_i64(row, column)?).map_err(|_| MailDurablePersistenceError::InvalidRow)
}

fn row_bool(row: &PgRow, column: &str) -> Result<bool, MailDurablePersistenceError> {
    row.try_get(column)
        .map_err(|_| MailDurablePersistenceError::InvalidRow)
}

fn row_bytes(row: &PgRow, column: &str) -> Result<Vec<u8>, MailDurablePersistenceError> {
    row.try_get(column)
        .map_err(|_| MailDurablePersistenceError::InvalidRow)
}

const fn folder_kind_from_id(kind: i16) -> Result<MailFolderKindV1, MailDurablePersistenceError> {
    match kind {
        1 => Ok(MailFolderKindV1::Inbox),
        2 => Ok(MailFolderKindV1::Sent),
        3 => Ok(MailFolderKindV1::Drafts),
        4 => Ok(MailFolderKindV1::Trash),
        5 => Ok(MailFolderKindV1::Spam),
        6 => Ok(MailFolderKindV1::Archive),
        7 => Ok(MailFolderKindV1::ProviderLabel),
        _ => Err(MailDurablePersistenceError::InvalidRow),
    }
}

const fn message_flag_from_id(flag: i16) -> Result<MailMessageFlagV1, MailDurablePersistenceError> {
    match flag {
        1 => Ok(MailMessageFlagV1::Read),
        2 => Ok(MailMessageFlagV1::Starred),
        3 => Ok(MailMessageFlagV1::Draft),
        4 => Ok(MailMessageFlagV1::Sent),
        5 => Ok(MailMessageFlagV1::Trashed),
        6 => Ok(MailMessageFlagV1::Spam),
        _ => Err(MailDurablePersistenceError::InvalidRow),
    }
}

pub(crate) async fn record_operational_materializations_in_transaction(
    transaction: &mut Transaction<'_, Postgres>,
    materializations: &[MailOperationalMaterializationV1],
    observed_at_unix_seconds: i64,
) -> Result<(), MailDurablePersistenceError> {
    validate_materializations(materializations, observed_at_unix_seconds)?;
    for materialization in materializations {
        for record in &materialization.communications_outbox {
            insert_communications_outbox(transaction, record, observed_at_unix_seconds).await?;
        }
        upsert_operational_message(
            transaction,
            &materialization.message,
            observed_at_unix_seconds,
        )
        .await?;
        crate::delivery_intent::upsert_delivery_route_locator(
            transaction,
            &materialization.delivery_route_locator,
            observed_at_unix_seconds,
        )
        .await?;
    }
    Ok(())
}

fn validate_materializations(
    materializations: &[MailOperationalMaterializationV1],
    observed_at_unix_seconds: i64,
) -> Result<(), MailDurablePersistenceError> {
    if materializations.is_empty()
        || observed_at_unix_seconds <= 0
        || materializations.iter().any(|materialization| {
            let message = &materialization.message;
            let locator = &materialization.delivery_route_locator;
            let public = public_message(message);
            validate_operational_message(&public).is_err()
                || locator.connection_id != message.connection_id
                || locator.provider_thread_id != message.provider_thread_id
                || locator.provider_message_id != message.message_id
                || locator.sender != message.sender
                || locator.recipients != message.recipients
                || locator.subject != message.subject.clone().unwrap_or_default()
                || message
                    .imap_locator
                    .as_ref()
                    .is_some_and(|locator| validate_imap_locator(locator).is_err())
                || message
                    .folders
                    .iter()
                    .any(|folder| !valid_folder_snapshot(folder))
                || materialization.communications_outbox.is_empty()
                || materialization
                    .communications_outbox
                    .iter()
                    .filter(|record| record.message_id() == &message.observation_anchor_id)
                    .count()
                    != 1
        })
    {
        return Err(MailDurablePersistenceError::InvalidRow);
    }
    Ok(())
}

async fn upsert_operational_message(
    transaction: &mut Transaction<'_, Postgres>,
    message: &MailOperationalMessageSnapshotV1,
    observed_at_unix_seconds: i64,
) -> Result<(), MailDurablePersistenceError> {
    let old = sqlx::query(
        "SELECT provider_thread_id FROM hermes_data.mail_operational_messages \
         WHERE connection_id = $1 AND message_id = $2",
    )
    .bind(&message.connection_id)
    .bind(&message.message_id)
    .fetch_optional(&mut **transaction)
    .await
    .map_err(|_| MailDurablePersistenceError::Database)?;
    let old_thread_id = old
        .as_ref()
        .map(|row| row.try_get::<String, _>("provider_thread_id"))
        .transpose()
        .map_err(|_| MailDurablePersistenceError::InvalidRow)?;
    let old_folder_rows = sqlx::query(
        "SELECT folder_id FROM hermes_data.mail_operational_message_folders \
         WHERE connection_id = $1 AND message_id = $2",
    )
    .bind(&message.connection_id)
    .bind(&message.message_id)
    .fetch_all(&mut **transaction)
    .await
    .map_err(|_| MailDurablePersistenceError::Database)?;
    let mut affected_folders = old_folder_rows
        .iter()
        .map(|row| row.try_get::<String, _>("folder_id"))
        .collect::<Result<BTreeSet<_>, _>>()
        .map_err(|_| MailDurablePersistenceError::InvalidRow)?;

    for folder in &message.folders {
        affected_folders.insert(folder.folder_id.clone());
        upsert_operational_folder(
            transaction,
            &message.connection_id,
            folder,
            observed_at_unix_seconds,
        )
        .await?;
    }

    let recipients = message.recipients.clone();
    let flags = message
        .flags
        .iter()
        .map(|flag| message_flag_id(*flag))
        .collect::<Vec<_>>();
    sqlx::query(
        "INSERT INTO hermes_data.mail_operational_messages \
         (connection_id, provider_message_id, provider_thread_id, subject, sender, recipients, \
          snippet, sent_at_unix_seconds, flags, has_plain_text, has_attachments, \
          observation_anchor_id, updated_at_unix_seconds) \
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) \
         ON CONFLICT (connection_id, message_id) DO UPDATE SET \
           provider_thread_id = EXCLUDED.provider_thread_id, subject = EXCLUDED.subject, \
           sender = EXCLUDED.sender, recipients = EXCLUDED.recipients, snippet = EXCLUDED.snippet, \
           sent_at_unix_seconds = EXCLUDED.sent_at_unix_seconds, flags = EXCLUDED.flags, \
           has_plain_text = EXCLUDED.has_plain_text, has_attachments = EXCLUDED.has_attachments, \
           observation_anchor_id = EXCLUDED.observation_anchor_id, \
           projection_revision = CASE \
             WHEN (hermes_data.mail_operational_messages.provider_thread_id, \
                   hermes_data.mail_operational_messages.subject, \
                   hermes_data.mail_operational_messages.sender, \
                   hermes_data.mail_operational_messages.recipients, \
                   hermes_data.mail_operational_messages.snippet, \
                   hermes_data.mail_operational_messages.sent_at_unix_seconds, \
                   hermes_data.mail_operational_messages.flags, \
                   hermes_data.mail_operational_messages.has_plain_text, \
                   hermes_data.mail_operational_messages.has_attachments, \
                   hermes_data.mail_operational_messages.observation_anchor_id) \
                  IS DISTINCT FROM \
                  (EXCLUDED.provider_thread_id, EXCLUDED.subject, EXCLUDED.sender, \
                   EXCLUDED.recipients, EXCLUDED.snippet, EXCLUDED.sent_at_unix_seconds, \
                   EXCLUDED.flags, EXCLUDED.has_plain_text, EXCLUDED.has_attachments, \
                   EXCLUDED.observation_anchor_id) \
             THEN hermes_data.mail_operational_messages.projection_revision + 1 \
             ELSE hermes_data.mail_operational_messages.projection_revision END, \
           updated_at_unix_seconds = EXCLUDED.updated_at_unix_seconds",
    )
    .bind(&message.connection_id)
    .bind(&message.message_id)
    .bind(&message.provider_thread_id)
    .bind(&message.subject)
    .bind(&message.sender)
    .bind(recipients)
    .bind(&message.snippet)
    .bind(message.sent_at_unix_seconds)
    .bind(flags)
    .bind(message.has_plain_text)
    .bind(message.has_attachments)
    .bind(message.observation_anchor_id.as_slice())
    .bind(observed_at_unix_seconds)
    .execute(&mut **transaction)
    .await
    .map_err(|_| MailDurablePersistenceError::Database)?;

    if let Some(locator) = &message.imap_locator {
        upsert_imap_message_locator(
            transaction,
            &message.connection_id,
            &message.message_id,
            locator,
            observed_at_unix_seconds,
        )
        .await?;
    }

    sqlx::query(
        "DELETE FROM hermes_data.mail_operational_message_folders \
         WHERE connection_id = $1 AND message_id = $2",
    )
    .bind(&message.connection_id)
    .bind(&message.message_id)
    .execute(&mut **transaction)
    .await
    .map_err(|_| MailDurablePersistenceError::Database)?;
    for folder in &message.folders {
        sqlx::query(
            "INSERT INTO hermes_data.mail_operational_message_folders \
             (connection_id, provider_message_id, folder_id) VALUES ($1, $2, $3)",
        )
        .bind(&message.connection_id)
        .bind(&message.message_id)
        .bind(&folder.folder_id)
        .execute(&mut **transaction)
        .await
        .map_err(|_| MailDurablePersistenceError::Database)?;
    }

    refresh_thread(
        transaction,
        &message.connection_id,
        &message.provider_thread_id,
        observed_at_unix_seconds,
    )
    .await?;
    if let Some(old_thread_id) = old_thread_id
        && old_thread_id != message.provider_thread_id
    {
        refresh_thread(
            transaction,
            &message.connection_id,
            &old_thread_id,
            observed_at_unix_seconds,
        )
        .await?;
    }
    for folder_id in affected_folders {
        refresh_folder(
            transaction,
            &message.connection_id,
            &folder_id,
            observed_at_unix_seconds,
        )
        .await?;
    }
    Ok(())
}

pub(crate) async fn refresh_thread(
    transaction: &mut Transaction<'_, Postgres>,
    connection_id: &str,
    provider_thread_id: &str,
    observed_at_unix_seconds: i64,
) -> Result<(), MailDurablePersistenceError> {
    let result = sqlx::query(
        "WITH aggregate AS ( \
           SELECT COUNT(*)::BIGINT AS message_count, \
             COUNT(*) FILTER (WHERE NOT (1 = ANY(flags)))::BIGINT AS unread_count \
           FROM hermes_data.mail_operational_messages \
           WHERE connection_id = $1 AND provider_thread_id = $2 \
         ), latest AS ( \
           SELECT subject, snippet, sent_at_unix_seconds \
           FROM hermes_data.mail_operational_messages \
           WHERE connection_id = $1 AND provider_thread_id = $2 \
           ORDER BY sent_at_unix_seconds DESC NULLS LAST, \
             updated_at_unix_seconds DESC, message_id DESC LIMIT 1 \
         ) \
         INSERT INTO hermes_data.mail_operational_threads \
           (connection_id, provider_thread_id, subject, latest_snippet, latest_at_unix_seconds, \
            message_count, unread_count, updated_at_unix_seconds) \
         SELECT $1, $2, latest.subject, latest.snippet, latest.sent_at_unix_seconds, \
           aggregate.message_count, aggregate.unread_count, $3 FROM aggregate, latest \
         ON CONFLICT (connection_id, provider_thread_id) DO UPDATE SET \
           subject = EXCLUDED.subject, latest_snippet = EXCLUDED.latest_snippet, \
           latest_at_unix_seconds = EXCLUDED.latest_at_unix_seconds, \
           message_count = EXCLUDED.message_count, unread_count = EXCLUDED.unread_count, \
           projection_revision = CASE \
             WHEN (hermes_data.mail_operational_threads.subject, \
                   hermes_data.mail_operational_threads.latest_snippet, \
                   hermes_data.mail_operational_threads.latest_at_unix_seconds, \
                   hermes_data.mail_operational_threads.message_count, \
                   hermes_data.mail_operational_threads.unread_count) \
                  IS DISTINCT FROM \
                  (EXCLUDED.subject, EXCLUDED.latest_snippet, EXCLUDED.latest_at_unix_seconds, \
                   EXCLUDED.message_count, EXCLUDED.unread_count) \
             THEN hermes_data.mail_operational_threads.projection_revision + 1 \
             ELSE hermes_data.mail_operational_threads.projection_revision END, \
           updated_at_unix_seconds = EXCLUDED.updated_at_unix_seconds",
    )
    .bind(connection_id)
    .bind(provider_thread_id)
    .bind(observed_at_unix_seconds)
    .execute(&mut **transaction)
    .await
    .map_err(|_| MailDurablePersistenceError::Database)?;
    if result.rows_affected() == 0 {
        sqlx::query(
            "DELETE FROM hermes_data.mail_operational_threads \
             WHERE connection_id = $1 AND provider_thread_id = $2",
        )
        .bind(connection_id)
        .bind(provider_thread_id)
        .execute(&mut **transaction)
        .await
        .map_err(|_| MailDurablePersistenceError::Database)?;
    }
    Ok(())
}

pub(crate) async fn refresh_folder(
    transaction: &mut Transaction<'_, Postgres>,
    connection_id: &str,
    folder_id: &str,
    observed_at_unix_seconds: i64,
) -> Result<(), MailDurablePersistenceError> {
    sqlx::query(
        "UPDATE hermes_data.mail_operational_folders AS folder SET \
           total_messages = counts.total_messages, unread_messages = counts.unread_messages, \
           projection_revision = CASE \
             WHEN (folder.total_messages, folder.unread_messages) \
                  IS DISTINCT FROM (counts.total_messages, counts.unread_messages) \
             THEN folder.projection_revision + 1 ELSE folder.projection_revision END, \
           updated_at_unix_seconds = $3 \
         FROM ( \
           SELECT COUNT(*)::BIGINT AS total_messages, \
             COUNT(*) FILTER (WHERE NOT (1 = ANY(message.flags)))::BIGINT AS unread_messages \
           FROM hermes_data.mail_operational_message_folders AS membership \
           JOIN hermes_data.mail_operational_messages AS message \
             ON message.connection_id = membership.connection_id \
            AND message.message_id = membership.message_id \
           WHERE membership.connection_id = $1 AND membership.folder_id = $2 \
         ) AS counts \
         WHERE folder.connection_id = $1 AND folder.folder_id = $2",
    )
    .bind(connection_id)
    .bind(folder_id)
    .bind(observed_at_unix_seconds)
    .execute(&mut **transaction)
    .await
    .map(|_| ())
    .map_err(|_| MailDurablePersistenceError::Database)
}

pub(crate) async fn upsert_operational_folder(
    transaction: &mut Transaction<'_, Postgres>,
    connection_id: &str,
    folder: &MailOperationalFolderSnapshotV1,
    observed_at_unix_seconds: i64,
) -> Result<(), MailDurablePersistenceError> {
    if !valid_folder_snapshot(folder) {
        return Err(MailDurablePersistenceError::InvalidRow);
    }
    sqlx::query(
        "INSERT INTO hermes_data.mail_operational_folders \
         (connection_id, folder_id, display_name, kind, updated_at_unix_seconds) \
         VALUES ($1, $2, $3, $4, $5) \
         ON CONFLICT (connection_id, folder_id) DO UPDATE SET \
           display_name = EXCLUDED.display_name, kind = EXCLUDED.kind, \
           projection_revision = CASE \
             WHEN (hermes_data.mail_operational_folders.display_name, \
                   hermes_data.mail_operational_folders.kind) \
                  IS DISTINCT FROM (EXCLUDED.display_name, EXCLUDED.kind) \
             THEN hermes_data.mail_operational_folders.projection_revision + 1 \
             ELSE hermes_data.mail_operational_folders.projection_revision END, \
           updated_at_unix_seconds = EXCLUDED.updated_at_unix_seconds",
    )
    .bind(connection_id)
    .bind(&folder.folder_id)
    .bind(&folder.display_name)
    .bind(folder_kind_id(folder.kind))
    .bind(observed_at_unix_seconds)
    .execute(&mut **transaction)
    .await
    .map(|_| ())
    .map_err(|_| MailDurablePersistenceError::Database)
}

fn valid_folder_snapshot(folder: &MailOperationalFolderSnapshotV1) -> bool {
    !folder.folder_id.trim().is_empty()
        && folder.folder_id.len() <= 512
        && folder.folder_id.trim() == folder.folder_id
        && !folder.folder_id.contains(['\0', '\r', '\n'])
        && !folder.display_name.trim().is_empty()
        && folder.display_name.len() <= 512
        && !folder.display_name.contains(['\0', '\r', '\n'])
}

fn public_message(message: &MailOperationalMessageSnapshotV1) -> MailMessageSummaryV1 {
    MailMessageSummaryV1 {
        connection_id: message.connection_id.clone(),
        message_id: message.message_id.clone(),
        provider_thread_id: message.provider_thread_id.clone(),
        folder_ids: message
            .folders
            .iter()
            .map(|folder| folder.folder_id.clone())
            .collect(),
        subject: message.subject.clone(),
        sender: message.sender.clone(),
        recipients: message.recipients.clone(),
        snippet: message.snippet.clone(),
        sent_at_unix_seconds: message.sent_at_unix_seconds,
        flags: message.flags.clone(),
        has_plain_text: message.has_plain_text,
        has_attachments: message.has_attachments,
        observation_anchor_id: message.observation_anchor_id,
        projection_revision: 1,
    }
}

const fn folder_kind_id(kind: MailFolderKindV1) -> i16 {
    match kind {
        MailFolderKindV1::Inbox => 1,
        MailFolderKindV1::Sent => 2,
        MailFolderKindV1::Drafts => 3,
        MailFolderKindV1::Trash => 4,
        MailFolderKindV1::Spam => 5,
        MailFolderKindV1::Archive => 6,
        MailFolderKindV1::ProviderLabel => 7,
    }
}

const fn message_flag_id(flag: MailMessageFlagV1) -> i16 {
    match flag {
        MailMessageFlagV1::Read => 1,
        MailMessageFlagV1::Starred => 2,
        MailMessageFlagV1::Draft => 3,
        MailMessageFlagV1::Sent => 4,
        MailMessageFlagV1::Trashed => 5,
        MailMessageFlagV1::Spam => 6,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn schema_is_owner_local_and_projection_only() {
        assert_eq!(
            MAIL_SCHEMA_V9
                .matches("CREATE TABLE IF NOT EXISTS ")
                .count(),
            4
        );
        assert_eq!(
            MAIL_SCHEMA_V9
                .matches("CREATE TABLE IF NOT EXISTS hermes_data.mail_")
                .count(),
            4
        );
        assert!(!MAIL_SCHEMA_V9.contains("communications_"));
        assert!(!MAIL_SCHEMA_V9.contains("password"));
        assert!(!MAIL_SCHEMA_V9.contains("provider_cursor"));
    }

    #[test]
    fn flags_have_exact_stable_storage_ids() {
        assert_eq!(message_flag_id(MailMessageFlagV1::Read), 1);
        assert_eq!(message_flag_id(MailMessageFlagV1::Spam), 6);
        assert_eq!(folder_kind_id(MailFolderKindV1::Inbox), 1);
        assert_eq!(folder_kind_id(MailFolderKindV1::ProviderLabel), 7);
    }

    #[test]
    fn cursor_is_query_scoped_and_does_not_expose_provider_identity() {
        let inbox_scope = cursor_scope(&["messages", "account-1", "INBOX", ""]);
        let sent_scope = cursor_scope(&["messages", "account-1", "SENT", ""]);
        assert_ne!(inbox_scope, sent_scope);

        let cursor = format!("m2m.{inbox_scope}.1700000000.42");
        assert_eq!(
            decode_cursor("m2m", &inbox_scope, Some(&cursor)),
            Ok(CursorAnchorV1 {
                updated_at_unix_seconds: 1_700_000_000,
                sequence: 42,
            })
        );
        assert_eq!(
            decode_cursor("m2m", &sent_scope, Some(&cursor)),
            Err(MailDurablePersistenceError::InvalidRow)
        );
        assert!(!cursor.contains("account-1"));
        assert!(!cursor.contains("INBOX"));
        assert!(cursor.len() < hermes_mail_api::operational::MAX_OPERATIONAL_CURSOR_BYTES);
    }
}
