//! Mail-owned restart-safe sync run journal and bounded health queries.

use makosh_mail_api::sync_health::{
    MailSyncFailureCodeV1, MailSyncHealthQueryResponseV1, MailSyncHealthQueryV1, MailSyncOutcomeV1,
    MailSyncProviderPathReadinessV1, MailSyncRunPageV1, MailSyncRunV1, MailSyncStatusV1,
    MailSyncTriggerV1, validate_sync_health_query, validate_sync_run,
};
use sha2::{Digest, Sha256};
use sqlx::{Postgres, Row, Transaction, postgres::PgRow};

use crate::{MailDurablePersistence, MailDurablePersistenceError};

pub const MAIL_SCHEMA_V10: &str = r#"
CREATE TABLE IF NOT EXISTS makosh_data.mail_sync_runs (
    operation_id TEXT PRIMARY KEY,
    connection_id TEXT NOT NULL,
    trigger SMALLINT NOT NULL,
    outcome SMALLINT NOT NULL,
    observed_messages BIGINT NOT NULL DEFAULT 0,
    started_at_unix_seconds BIGINT NOT NULL,
    completed_at_unix_seconds BIGINT,
    failure_code SMALLINT,
    runtime_generation BIGINT NOT NULL,
    projection_revision BIGINT NOT NULL DEFAULT 1,
    cursor_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    UNIQUE (connection_id, operation_id),
    CHECK (operation_id <> ''),
    CHECK (connection_id <> ''),
    CHECK (trigger BETWEEN 1 AND 2),
    CHECK (outcome BETWEEN 1 AND 4),
    CHECK (observed_messages >= 0),
    CHECK (started_at_unix_seconds > 0),
    CHECK (completed_at_unix_seconds IS NULL OR completed_at_unix_seconds >= started_at_unix_seconds),
    CHECK (failure_code IS NULL OR failure_code BETWEEN 1 AND 9),
    CHECK (runtime_generation > 0),
    CHECK (projection_revision > 0),
    CHECK (
        (outcome = 1 AND completed_at_unix_seconds IS NULL AND failure_code IS NULL)
        OR (outcome = 2 AND completed_at_unix_seconds IS NOT NULL AND failure_code IS NULL)
        OR (outcome IN (3, 4) AND completed_at_unix_seconds IS NOT NULL AND failure_code IS NOT NULL)
    )
);
CREATE UNIQUE INDEX IF NOT EXISTS mail_sync_runs_one_current_per_connection_idx
    ON makosh_data.mail_sync_runs (connection_id)
    WHERE outcome = 1;
CREATE INDEX IF NOT EXISTS mail_sync_runs_cursor_idx
    ON makosh_data.mail_sync_runs
    (connection_id, started_at_unix_seconds DESC, cursor_sequence DESC);
CREATE TABLE IF NOT EXISTS makosh_data.mail_sync_status (
    connection_id TEXT PRIMARY KEY,
    latest_operation_id TEXT NOT NULL,
    consecutive_failures BIGINT NOT NULL DEFAULT 0,
    last_success_at_unix_seconds BIGINT,
    projection_revision BIGINT NOT NULL DEFAULT 1,
    updated_at_unix_seconds BIGINT NOT NULL,
    FOREIGN KEY (connection_id, latest_operation_id)
        REFERENCES makosh_data.mail_sync_runs (connection_id, operation_id)
        ON DELETE RESTRICT,
    CHECK (connection_id <> ''),
    CHECK (latest_operation_id <> ''),
    CHECK (consecutive_failures >= 0),
    CHECK (last_success_at_unix_seconds IS NULL OR last_success_at_unix_seconds > 0),
    CHECK (projection_revision > 0),
    CHECK (updated_at_unix_seconds > 0)
);
"#;

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum MailSyncRunStartOutcomeV1 {
    Started(MailSyncRunV1),
    ExistingRunning(MailSyncRunV1),
    ExistingTerminal(MailSyncRunV1),
}

impl MailDurablePersistence {
    pub async fn begin_sync_run(
        &self,
        operation_id: &str,
        connection_id: &str,
        trigger: MailSyncTriggerV1,
        runtime_generation: u64,
        started_at_unix_seconds: i64,
    ) -> Result<MailSyncRunStartOutcomeV1, MailDurablePersistenceError> {
        let run = MailSyncRunV1 {
            operation_id: operation_id.to_owned(),
            connection_id: connection_id.to_owned(),
            trigger,
            outcome: MailSyncOutcomeV1::Running,
            observed_messages: 0,
            started_at_unix_seconds,
            completed_at_unix_seconds: None,
            failure_code: None,
            runtime_generation,
            projection_revision: 1,
        };
        validate_sync_run(&run).map_err(|_| MailDurablePersistenceError::InvalidRow)?;
        let mut transaction = self
            .pool
            .begin()
            .await
            .map_err(|_| MailDurablePersistenceError::Database)?;
        if let Some(existing) = sync_run_for_update(&mut transaction, operation_id).await? {
            if existing.connection_id != connection_id {
                return Err(MailDurablePersistenceError::ConflictingSyncOperation);
            }
            return if existing.outcome == MailSyncOutcomeV1::Running {
                Ok(MailSyncRunStartOutcomeV1::ExistingRunning(existing))
            } else {
                Ok(MailSyncRunStartOutcomeV1::ExistingTerminal(existing))
            };
        }
        let current = sqlx::query(
            "SELECT operation_id FROM makosh_data.mail_sync_runs
             WHERE connection_id = $1 AND outcome = 1 FOR UPDATE",
        )
        .bind(connection_id)
        .fetch_optional(&mut *transaction)
        .await
        .map_err(|_| MailDurablePersistenceError::Database)?;
        if current.is_some() {
            return Err(MailDurablePersistenceError::SyncRunInProgress);
        }
        sqlx::query(
            "INSERT INTO makosh_data.mail_sync_runs
             (operation_id, connection_id, trigger, outcome, observed_messages,
              started_at_unix_seconds, runtime_generation, projection_revision)
             VALUES ($1, $2, $3, 1, 0, $4, $5, 1)",
        )
        .bind(operation_id)
        .bind(connection_id)
        .bind(trigger_id(trigger))
        .bind(started_at_unix_seconds)
        .bind(
            i64::try_from(runtime_generation)
                .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        )
        .execute(&mut *transaction)
        .await
        .map_err(map_begin_error)?;
        sqlx::query(
            "INSERT INTO makosh_data.mail_sync_status
             (connection_id, latest_operation_id, updated_at_unix_seconds)
             VALUES ($1, $2, $3)
             ON CONFLICT (connection_id) DO UPDATE
             SET latest_operation_id = EXCLUDED.latest_operation_id,
                 projection_revision = makosh_data.mail_sync_status.projection_revision + 1,
                 updated_at_unix_seconds = EXCLUDED.updated_at_unix_seconds",
        )
        .bind(connection_id)
        .bind(operation_id)
        .bind(started_at_unix_seconds)
        .execute(&mut *transaction)
        .await
        .map_err(|_| MailDurablePersistenceError::Database)?;
        transaction
            .commit()
            .await
            .map_err(|_| MailDurablePersistenceError::Database)?;
        Ok(MailSyncRunStartOutcomeV1::Started(run))
    }

    pub async fn complete_sync_run(
        &self,
        operation_id: &str,
        outcome: MailSyncOutcomeV1,
        observed_messages: u64,
        failure_code: Option<MailSyncFailureCodeV1>,
        completed_at_unix_seconds: i64,
    ) -> Result<MailSyncRunV1, MailDurablePersistenceError> {
        if !matches!(
            outcome,
            MailSyncOutcomeV1::Succeeded | MailSyncOutcomeV1::Failed
        ) {
            return Err(MailDurablePersistenceError::InvalidSyncTransition);
        }
        let mut transaction = self
            .pool
            .begin()
            .await
            .map_err(|_| MailDurablePersistenceError::Database)?;
        let existing = sync_run_for_update(&mut transaction, operation_id)
            .await?
            .ok_or(MailDurablePersistenceError::MissingSyncRun)?;
        if existing.outcome != MailSyncOutcomeV1::Running {
            if existing.outcome == outcome
                && existing.observed_messages == observed_messages
                && existing.failure_code == failure_code
                && existing.completed_at_unix_seconds == Some(completed_at_unix_seconds)
            {
                return Ok(existing);
            }
            return Err(MailDurablePersistenceError::InvalidSyncTransition);
        }
        let completed_at = completed_at_unix_seconds.max(existing.started_at_unix_seconds);
        let completed = MailSyncRunV1 {
            outcome,
            observed_messages,
            completed_at_unix_seconds: Some(completed_at),
            failure_code,
            projection_revision: existing.projection_revision.saturating_add(1),
            ..existing
        };
        validate_sync_run(&completed).map_err(|_| MailDurablePersistenceError::InvalidRow)?;
        sqlx::query(
            "UPDATE makosh_data.mail_sync_runs
             SET outcome = $2, observed_messages = $3, completed_at_unix_seconds = $4,
                 failure_code = $5, deadline_exceeded = $6,
                 projection_revision = projection_revision + 1
             WHERE operation_id = $1 AND outcome = 1",
        )
        .bind(operation_id)
        .bind(outcome_id(outcome))
        .bind(
            i64::try_from(observed_messages)
                .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        )
        .bind(completed_at)
        .bind(failure_code.map(storage_failure_id))
        .bind(matches!(
            failure_code,
            Some(MailSyncFailureCodeV1::DeadlineExceeded)
        ))
        .execute(&mut *transaction)
        .await
        .map_err(|_| MailDurablePersistenceError::Database)?;
        update_status_after_completion(&mut transaction, &completed, completed_at).await?;
        transaction
            .commit()
            .await
            .map_err(|_| MailDurablePersistenceError::Database)?;
        Ok(completed)
    }

    pub async fn interrupt_stale_sync_runs(
        &self,
        current_runtime_generation: u64,
        interrupted_at_unix_seconds: i64,
    ) -> Result<u64, MailDurablePersistenceError> {
        if current_runtime_generation == 0 || interrupted_at_unix_seconds <= 0 {
            return Err(MailDurablePersistenceError::InvalidRow);
        }
        let generation = i64::try_from(current_runtime_generation)
            .map_err(|_| MailDurablePersistenceError::InvalidRow)?;
        let mut transaction = self
            .pool
            .begin()
            .await
            .map_err(|_| MailDurablePersistenceError::Database)?;
        let rows = sqlx::query(
            "UPDATE makosh_data.mail_sync_runs
             SET outcome = 4,
                 completed_at_unix_seconds = GREATEST(started_at_unix_seconds, $2),
                 failure_code = 9,
                 projection_revision = projection_revision + 1
             WHERE outcome = 1 AND runtime_generation <> $1
             RETURNING connection_id",
        )
        .bind(generation)
        .bind(interrupted_at_unix_seconds)
        .fetch_all(&mut *transaction)
        .await
        .map_err(|_| MailDurablePersistenceError::Database)?;
        for row in &rows {
            let connection_id: String = row
                .try_get("connection_id")
                .map_err(|_| MailDurablePersistenceError::InvalidRow)?;
            sqlx::query(
                "UPDATE makosh_data.mail_sync_status
                 SET consecutive_failures = consecutive_failures + 1,
                     projection_revision = projection_revision + 1,
                     updated_at_unix_seconds = GREATEST(updated_at_unix_seconds, $2)
                 WHERE connection_id = $1",
            )
            .bind(connection_id)
            .bind(interrupted_at_unix_seconds)
            .execute(&mut *transaction)
            .await
            .map_err(|_| MailDurablePersistenceError::Database)?;
        }
        transaction
            .commit()
            .await
            .map_err(|_| MailDurablePersistenceError::Database)?;
        u64::try_from(rows.len()).map_err(|_| MailDurablePersistenceError::InvalidRow)
    }

    pub async fn execute_sync_health_query(
        &self,
        query: &MailSyncHealthQueryV1,
        readiness: MailSyncProviderPathReadinessV1,
    ) -> Result<MailSyncHealthQueryResponseV1, MailDurablePersistenceError> {
        validate_sync_health_query(query).map_err(|_| MailDurablePersistenceError::InvalidRow)?;
        match query {
            MailSyncHealthQueryV1::GetStatus { connection_id } => self
                .sync_status(connection_id, readiness)
                .await
                .map(MailSyncHealthQueryResponseV1::Status),
            MailSyncHealthQueryV1::ListRuns {
                connection_id,
                cursor,
                limit,
            } => self
                .list_sync_runs(connection_id, cursor.as_deref(), *limit)
                .await
                .map(MailSyncHealthQueryResponseV1::Runs),
            MailSyncHealthQueryV1::GetRun {
                connection_id,
                operation_id,
            } => self
                .sync_run(connection_id, operation_id)
                .await
                .map(MailSyncHealthQueryResponseV1::Run),
        }
    }

    async fn sync_run(
        &self,
        connection_id: &str,
        operation_id: &str,
    ) -> Result<Option<MailSyncRunV1>, MailDurablePersistenceError> {
        sqlx::query(
            "SELECT operation_id, connection_id, trigger, outcome, observed_messages,
                    started_at_unix_seconds, completed_at_unix_seconds, failure_code,
                    deadline_exceeded, runtime_generation, projection_revision
             FROM makosh_data.mail_sync_runs
             WHERE connection_id = $1 AND operation_id = $2",
        )
        .bind(connection_id)
        .bind(operation_id)
        .fetch_optional(&self.pool)
        .await
        .map_err(|_| MailDurablePersistenceError::Database)?
        .as_ref()
        .map(run_from_row)
        .transpose()
    }

    async fn list_sync_runs(
        &self,
        connection_id: &str,
        cursor: Option<&str>,
        limit: u32,
    ) -> Result<MailSyncRunPageV1, MailDurablePersistenceError> {
        let anchor = cursor
            .map(|value| decode_cursor(connection_id, value))
            .transpose()?;
        let fetch_limit = i64::from(limit) + 1;
        let rows = if let Some(anchor) = anchor {
            sqlx::query(
                "SELECT operation_id, connection_id, trigger, outcome, observed_messages,
                        started_at_unix_seconds, completed_at_unix_seconds, failure_code,
                        deadline_exceeded, runtime_generation, projection_revision, cursor_sequence
                 FROM makosh_data.mail_sync_runs
                 WHERE connection_id = $1
                   AND (started_at_unix_seconds, cursor_sequence) < ($2, $3)
                 ORDER BY started_at_unix_seconds DESC, cursor_sequence DESC
                 LIMIT $4",
            )
            .bind(connection_id)
            .bind(anchor.started_at_unix_seconds)
            .bind(anchor.cursor_sequence)
            .bind(fetch_limit)
            .fetch_all(&self.pool)
            .await
        } else {
            sqlx::query(
                "SELECT operation_id, connection_id, trigger, outcome, observed_messages,
                        started_at_unix_seconds, completed_at_unix_seconds, failure_code,
                        deadline_exceeded, runtime_generation, projection_revision, cursor_sequence
                 FROM makosh_data.mail_sync_runs
                 WHERE connection_id = $1
                 ORDER BY started_at_unix_seconds DESC, cursor_sequence DESC
                 LIMIT $2",
            )
            .bind(connection_id)
            .bind(fetch_limit)
            .fetch_all(&self.pool)
            .await
        }
        .map_err(|_| MailDurablePersistenceError::Database)?;
        let visible_count = rows.len().min(limit as usize);
        let visible = &rows[..visible_count];
        let items = visible
            .iter()
            .map(run_from_row)
            .collect::<Result<Vec<_>, _>>()?;
        let next_cursor = if rows.len() > visible_count {
            visible
                .last()
                .map(|row| {
                    encode_cursor(
                        connection_id,
                        row.try_get("started_at_unix_seconds")
                            .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
                        row.try_get("cursor_sequence")
                            .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
                    )
                })
                .transpose()?
        } else {
            None
        };
        Ok(MailSyncRunPageV1 { items, next_cursor })
    }

    async fn sync_status(
        &self,
        connection_id: &str,
        readiness: MailSyncProviderPathReadinessV1,
    ) -> Result<MailSyncStatusV1, MailDurablePersistenceError> {
        let row = sqlx::query(
            "SELECT latest_operation_id, consecutive_failures,
                    last_success_at_unix_seconds, projection_revision
             FROM makosh_data.mail_sync_status WHERE connection_id = $1",
        )
        .bind(connection_id)
        .fetch_optional(&self.pool)
        .await
        .map_err(|_| MailDurablePersistenceError::Database)?;
        let Some(row) = row else {
            return Ok(MailSyncStatusV1 {
                connection_id: connection_id.to_owned(),
                provider_path_readiness: readiness,
                latest_run: None,
                consecutive_failures: 0,
                last_success_at_unix_seconds: None,
                projection_revision: 1,
            });
        };
        let operation_id: String = row
            .try_get("latest_operation_id")
            .map_err(|_| MailDurablePersistenceError::InvalidRow)?;
        let latest_run = self
            .sync_run(connection_id, &operation_id)
            .await?
            .ok_or(MailDurablePersistenceError::MissingSyncRun)?;
        Ok(MailSyncStatusV1 {
            connection_id: connection_id.to_owned(),
            provider_path_readiness: readiness,
            latest_run: Some(Box::new(latest_run)),
            consecutive_failures: u32::try_from(
                row.try_get::<i64, _>("consecutive_failures")
                    .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
            )
            .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
            last_success_at_unix_seconds: row
                .try_get("last_success_at_unix_seconds")
                .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
            projection_revision: u64::try_from(
                row.try_get::<i64, _>("projection_revision")
                    .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
            )
            .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        })
    }
}

async fn update_status_after_completion(
    transaction: &mut Transaction<'_, Postgres>,
    run: &MailSyncRunV1,
    completed_at: i64,
) -> Result<(), MailDurablePersistenceError> {
    let result = if run.outcome == MailSyncOutcomeV1::Succeeded {
        sqlx::query(
            "UPDATE makosh_data.mail_sync_status
             SET consecutive_failures = 0,
                 last_success_at_unix_seconds = $2,
                 projection_revision = projection_revision + 1,
                 updated_at_unix_seconds = $2
             WHERE connection_id = $1",
        )
        .bind(&run.connection_id)
        .bind(completed_at)
        .execute(&mut **transaction)
        .await
    } else {
        sqlx::query(
            "UPDATE makosh_data.mail_sync_status
             SET consecutive_failures = consecutive_failures + 1,
                 projection_revision = projection_revision + 1,
                 updated_at_unix_seconds = $2
             WHERE connection_id = $1",
        )
        .bind(&run.connection_id)
        .bind(completed_at)
        .execute(&mut **transaction)
        .await
    };
    result
        .map(|_| ())
        .map_err(|_| MailDurablePersistenceError::Database)
}

async fn sync_run_for_update(
    transaction: &mut Transaction<'_, Postgres>,
    operation_id: &str,
) -> Result<Option<MailSyncRunV1>, MailDurablePersistenceError> {
    sqlx::query(
        "SELECT operation_id, connection_id, trigger, outcome, observed_messages,
                started_at_unix_seconds, completed_at_unix_seconds, failure_code,
                deadline_exceeded, runtime_generation, projection_revision
         FROM makosh_data.mail_sync_runs WHERE operation_id = $1 FOR UPDATE",
    )
    .bind(operation_id)
    .fetch_optional(&mut **transaction)
    .await
    .map_err(|_| MailDurablePersistenceError::Database)?
    .as_ref()
    .map(run_from_row)
    .transpose()
}

fn run_from_row(row: &PgRow) -> Result<MailSyncRunV1, MailDurablePersistenceError> {
    let run = MailSyncRunV1 {
        operation_id: row
            .try_get("operation_id")
            .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        connection_id: row
            .try_get("connection_id")
            .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        trigger: trigger_from_id(
            row.try_get("trigger")
                .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        )?,
        outcome: outcome_from_id(
            row.try_get("outcome")
                .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        )?,
        observed_messages: u64::try_from(
            row.try_get::<i64, _>("observed_messages")
                .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        )
        .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        started_at_unix_seconds: row
            .try_get("started_at_unix_seconds")
            .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        completed_at_unix_seconds: row
            .try_get("completed_at_unix_seconds")
            .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        failure_code: failure_from_storage_row(row)?,
        runtime_generation: u64::try_from(
            row.try_get::<i64, _>("runtime_generation")
                .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        )
        .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        projection_revision: u64::try_from(
            row.try_get::<i64, _>("projection_revision")
                .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        )
        .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
    };
    validate_sync_run(&run).map_err(|_| MailDurablePersistenceError::InvalidRow)?;
    Ok(run)
}

fn map_begin_error(error: sqlx::Error) -> MailDurablePersistenceError {
    if error
        .as_database_error()
        .and_then(|value| value.constraint())
        == Some("mail_sync_runs_one_current_per_connection_idx")
    {
        MailDurablePersistenceError::SyncRunInProgress
    } else {
        MailDurablePersistenceError::Database
    }
}

const fn trigger_id(value: MailSyncTriggerV1) -> i16 {
    match value {
        MailSyncTriggerV1::Manual => 1,
        MailSyncTriggerV1::Scheduled => 2,
    }
}

const fn trigger_from_id(value: i16) -> Result<MailSyncTriggerV1, MailDurablePersistenceError> {
    match value {
        1 => Ok(MailSyncTriggerV1::Manual),
        2 => Ok(MailSyncTriggerV1::Scheduled),
        _ => Err(MailDurablePersistenceError::InvalidRow),
    }
}

const fn outcome_id(value: MailSyncOutcomeV1) -> i16 {
    match value {
        MailSyncOutcomeV1::Running => 1,
        MailSyncOutcomeV1::Succeeded => 2,
        MailSyncOutcomeV1::Failed => 3,
        MailSyncOutcomeV1::Interrupted => 4,
    }
}

const fn outcome_from_id(value: i16) -> Result<MailSyncOutcomeV1, MailDurablePersistenceError> {
    match value {
        1 => Ok(MailSyncOutcomeV1::Running),
        2 => Ok(MailSyncOutcomeV1::Succeeded),
        3 => Ok(MailSyncOutcomeV1::Failed),
        4 => Ok(MailSyncOutcomeV1::Interrupted),
        _ => Err(MailDurablePersistenceError::InvalidRow),
    }
}

const fn failure_id(value: MailSyncFailureCodeV1) -> i16 {
    match value {
        MailSyncFailureCodeV1::AdmissionRejected => 1,
        MailSyncFailureCodeV1::ControlUnavailable => 2,
        MailSyncFailureCodeV1::StorageUnavailable => 3,
        MailSyncFailureCodeV1::CredentialUnavailable => 4,
        MailSyncFailureCodeV1::PersistenceUnavailable => 5,
        MailSyncFailureCodeV1::ProviderUnavailable => 6,
        MailSyncFailureCodeV1::EventHubUnavailable => 7,
        MailSyncFailureCodeV1::AttachmentAnchorUnavailable => 8,
        MailSyncFailureCodeV1::RuntimeRestarted => 9,
        MailSyncFailureCodeV1::DeadlineExceeded => 10,
    }
}

const fn storage_failure_id(value: MailSyncFailureCodeV1) -> i16 {
    match value {
        // Schema v10 admits IDs 1..=9. Revision 30 records the exact timeout
        // meaning in an additive marker while retaining the provider failure
        // category in the legacy constrained column.
        MailSyncFailureCodeV1::DeadlineExceeded => {
            failure_id(MailSyncFailureCodeV1::ProviderUnavailable)
        }
        value => failure_id(value),
    }
}

fn failure_from_storage_row(
    row: &PgRow,
) -> Result<Option<MailSyncFailureCodeV1>, MailDurablePersistenceError> {
    let deadline_exceeded = row
        .try_get::<bool, _>("deadline_exceeded")
        .map_err(|_| MailDurablePersistenceError::InvalidRow)?;
    let stored = row
        .try_get::<Option<i16>, _>("failure_code")
        .map_err(|_| MailDurablePersistenceError::InvalidRow)?;
    if deadline_exceeded {
        if stored != Some(failure_id(MailSyncFailureCodeV1::ProviderUnavailable)) {
            return Err(MailDurablePersistenceError::InvalidRow);
        }
        return Ok(Some(MailSyncFailureCodeV1::DeadlineExceeded));
    }
    stored.map(failure_from_id).transpose()
}

const fn failure_from_id(value: i16) -> Result<MailSyncFailureCodeV1, MailDurablePersistenceError> {
    match value {
        1 => Ok(MailSyncFailureCodeV1::AdmissionRejected),
        2 => Ok(MailSyncFailureCodeV1::ControlUnavailable),
        3 => Ok(MailSyncFailureCodeV1::StorageUnavailable),
        4 => Ok(MailSyncFailureCodeV1::CredentialUnavailable),
        5 => Ok(MailSyncFailureCodeV1::PersistenceUnavailable),
        6 => Ok(MailSyncFailureCodeV1::ProviderUnavailable),
        7 => Ok(MailSyncFailureCodeV1::EventHubUnavailable),
        8 => Ok(MailSyncFailureCodeV1::AttachmentAnchorUnavailable),
        9 => Ok(MailSyncFailureCodeV1::RuntimeRestarted),
        10 => Ok(MailSyncFailureCodeV1::DeadlineExceeded),
        _ => Err(MailDurablePersistenceError::InvalidRow),
    }
}

#[derive(Clone, Copy)]
struct CursorAnchorV1 {
    started_at_unix_seconds: i64,
    cursor_sequence: i64,
}

fn encode_cursor(
    connection_id: &str,
    started_at_unix_seconds: i64,
    cursor_sequence: i64,
) -> Result<String, MailDurablePersistenceError> {
    if started_at_unix_seconds <= 0 || cursor_sequence <= 0 {
        return Err(MailDurablePersistenceError::InvalidRow);
    }
    Ok(format!(
        "v1.{}.{started_at_unix_seconds}.{cursor_sequence}",
        cursor_scope(connection_id)
    ))
}

fn decode_cursor(
    connection_id: &str,
    cursor: &str,
) -> Result<CursorAnchorV1, MailDurablePersistenceError> {
    let parts = cursor.split('.').collect::<Vec<_>>();
    if parts.len() != 4 || parts[0] != "v1" || parts[1] != cursor_scope(connection_id) {
        return Err(MailDurablePersistenceError::InvalidRow);
    }
    let anchor = CursorAnchorV1 {
        started_at_unix_seconds: parts[2]
            .parse()
            .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
        cursor_sequence: parts[3]
            .parse()
            .map_err(|_| MailDurablePersistenceError::InvalidRow)?,
    };
    if anchor.started_at_unix_seconds <= 0 || anchor.cursor_sequence <= 0 {
        return Err(MailDurablePersistenceError::InvalidRow);
    }
    Ok(anchor)
}

fn cursor_scope(connection_id: &str) -> String {
    let digest = Sha256::digest(format!("mail-sync-health-v1\0{connection_id}").as_bytes());
    digest[..16]
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn schema_is_mail_owned_and_has_exact_current_run_guard() {
        assert!(MAIL_SCHEMA_V10.contains("makosh_data.mail_sync_runs"));
        assert!(MAIL_SCHEMA_V10.contains("makosh_data.mail_sync_status"));
        assert!(MAIL_SCHEMA_V10.contains("WHERE outcome = 1"));
        assert!(!MAIL_SCHEMA_V10.contains("communications"));
        assert!(!MAIL_SCHEMA_V10.contains("scheduler"));
        assert!(!MAIL_SCHEMA_V10.contains("newsletter"));
    }

    #[test]
    fn cursor_is_connection_scoped_and_opaque() {
        let cursor = encode_cursor("account-1", 10, 11).expect("cursor");
        assert!(!cursor.contains("account-1"));
        assert!(decode_cursor("account-1", &cursor).is_ok());
        assert!(decode_cursor("account-2", &cursor).is_err());
    }

    #[test]
    fn deadline_failure_code_has_a_stable_storage_id() {
        assert_eq!(failure_id(MailSyncFailureCodeV1::DeadlineExceeded), 10);
        assert_eq!(
            storage_failure_id(MailSyncFailureCodeV1::DeadlineExceeded),
            failure_id(MailSyncFailureCodeV1::ProviderUnavailable)
        );
        assert_eq!(
            failure_from_id(10).expect("deadline failure storage ID"),
            MailSyncFailureCodeV1::DeadlineExceeded
        );
    }
}
