[alias]
makosh-nextest = "nextest run --manifest-path backend/Cargo.toml"
makosh-nextest-ci = "nextest run --manifest-path backend/Cargo.toml --profile ci"
makosh-nextest-integration = "nextest run --manifest-path backend/Cargo.toml --profile integration --tests"
makosh-llvm-cov = "llvm-cov --manifest-path backend/Cargo.toml"

[rust-analyzer]
checkOnSave = true
check.command = "clippy"
