[package]
name = "makosh-provider-orchestration"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
publish = false
license = "MIT"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
makosh-communications-api = { path = "../communications-api" }
makosh-provider-api = { path = "../provider-api" }
makosh-signal-hub-api = { path = "../signal-hub-api" }
serde_json = "1"
thiserror = "2"

[dev-dependencies]
